### ISSUE TITLE
When used from rails it is necessary to kill the process every request

### ISSUE THREAD

**Issue by joshrendek** [DavidHuie/quartz#23]
If you have code that instantiates a new client on each request, it is necessary to to kill it once the request is completed

```
    client = Quartz::Client.new(bin_path: 'go/packages')
    res = client[:packages].call('PendingUpdates', 'OrganizationID' => current_organization.id)

    client.instance_variable_get('@process').cleanup
```

Setting the client as a constant or a global in a rails initializers causes it to only spawn one, but after about 18 requests it will hang and the connection to the socket will timeout. This happens with both a go file and a go binary on OSX.

**Comment by DavidHuie** [comment]
Do you think it's Rails specific? I implement a test in https://github.com/DavidHuie/quartz/pull/24 that checks if we can process at least 100 calls. Also, an example that reproduces the error would be best.

**Comment by DavidHuie** [comment]
It might also be the case that #24 fixes the problem you were encountering.

**Comment by joshrendek** [comment]
#24 may fix it - I'd be glad to test it in my application once 0.2.6 is released. 

I think it would be specific to anything that received a request (in regards to spawning multiple processes).

As to why its freezing, I have no idea. Originally I thought it was because I was leaking DB connections in my code (which I fixed) but then it persisted.

**Comment by DavidHuie** [comment]
Cool. I'm going to release 0.2.6. Let me know if it helps.

**Comment by DavidHuie** [comment]
Closing this. Feel free to reopen it if you're still having problems, @joshrendek.
